version: '3.8'
services:
  backend:
    build:
      context: ./renesandro_app
    container_name: drf-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./PythonFrontRenesandro
    container_name: react-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

